Repository Pews-DEV/book-writer-backend, pull requests merged in 2022-04, with the labels that each got.

#3 Hotfix/user creation and authentication
  app/@types/express/index.d.ts
  app/authenticate/@types/index.ts
  app/authenticate/controller/AuthenticateUserController.ts
  app/authenticate/services/AuthenticateUserService.ts
  app/middlewares/IsAdmin.ts
  app/routers.ts
  app/user/controller/UserController.ts
  app/user/router/UserRouters.ts
  app/user/services/CreateUser.ts
  package.json
Labels: bug, available to review

#5 Feature/default setting
  .editorconfig
  .eslintignore
  .eslintrc
  .gitattributes
  .github/.workflows/ci.yml
  .husky/pre-commit
  .prettierignore
  .prettierrc
  .vscode/settings.json
  app/@types/express/index.d.ts
  app/authenticate/controller/AuthenticateUserController.ts
  app/authenticate/router/AutheticateUserRouter.ts
  app/authenticate/services/AuthenticateUserService.ts
  app/index.ts
  app/middlewares/@types/authentication.ts
  app/middlewares/IsAdmin.ts
  app/middlewares/IsAuthenticated.ts
  app/routers.ts
  app/src/database.ts
  app/src/migrations/1646863904590-User.ts
  app/user/@types/index.ts
  app/user/controller/UserController.ts
  app/user/controller/index.ts
  app/user/entities/User.ts
  app/user/repository/UserRepository.ts
  app/user/repository/index.ts
  app/user/router/UserRouters.ts
  app/user/services/CreateUser.ts
  app/user/services/index.ts
  jest.config.ts
  package.json
  yarn.lock
Labels: available to review

#4 Implementing user data validation
  .env.example
  .github/workflows/ci.yml
  app/errors/index.ts
  app/index.ts
  app/middlewares/IsAdmin.ts
  app/middlewares/IsAuthenticated.ts
  app/modules/authenticate/@types/index.ts
  app/modules/authenticate/controller/AuthenticateUserController.ts
  app/modules/authenticate/router/AutheticateUserRouter.ts
  app/modules/authenticate/services/AuthenticateUserService.ts
  app/modules/user/@types/index.ts
  app/modules/user/controller/UserController.ts
  app/modules/user/controller/index.ts
  app/modules/user/defaults.ts
  app/modules/user/repository/UserRepository.ts
  app/modules/user/repository/index.ts
  app/modules/user/routes.ts
  app/modules/user/services/CreateUser.ts
  app/modules/user/services/index.ts
  app/modules/user/validations/email.ts
  app/modules/user/validations/first_name.ts
  app/modules/user/validations/index.ts
  app/modules/user/validations/last_name.ts
  app/modules/user/validations/password.ts
  app/modules/user/validations/username.ts
  app/routers.ts
  app/src/entities/User.ts
  app/src/errorConfig.ts
  app/user/controller/UserController.ts
  app/user/entities/index.ts
  app/user/repository/UserRepository.ts
  app/user/router/UserRouters.ts
  app/user/services/CreateUser.ts
  app/utils/bcrypt/checkPassowrd.ts
  app/utils/bcrypt/hashPassword.ts
  app/utils/express-validator/getBodyField.ts
  app/utils/express-validator/getResult.ts
  ormconfig.json
  ormconfig.ts
  package.json
  tsconfig.json
  yarn.lock
Labels: enhancement, available to review
